/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.univali.l2s.plugin.corretor;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrei
 */
public class PainelQuestoes extends javax.swing.JPanel {
    
    private PluginCorretor pluginCorretor;
    private String[] columnNames = {"Título", "Status", "Nota", "Tentativas"};
    private DefaultTableModel dtm = new DefaultTableModel(columnNames, 0){
        // Deixa o table não-editável
        @Override
        public boolean isCellEditable(int row, int column){return false;}  
     };
    
    public PainelQuestoes(final PluginCorretor pluginCorretor) {
        this.pluginCorretor = pluginCorretor;
        iniciaTabela();
        initComponents();
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    pluginCorretor.questaoSelecionada = row;
                    pluginCorretor.estado = 1;
                    pluginCorretor.atualizaPainel();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Selecione um exercício:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void iniciaTabela() {
        for(PluginQuestao q : PluginCorretor.questoes){
            String status = "";
            switch(q.getStatus()){
                case PluginQuestao.EM_ABERTO:
                    status = "Em Aberto";
                    break;
                case PluginQuestao.PARCIAL:
                    status = "Parcial";
                    break;
                case PluginQuestao.FINALIZADO:
                    status = "Finalizado";
                    break;
            }
            Object[] colunas = new Object[4];
            colunas[0] = q.getQuestao().getTitulo();
            colunas[1] = status;
            colunas[2] = q.getMelhorNota();
            colunas[3] = q.getTentativas();
            dtm.addRow(colunas);
        }
    }
}
