/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.univali.l2s.plugin.corretor;

import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Andrei
 */
public class PainelQuestoes extends javax.swing.JPanel {
    
    private PluginCorretor pluginCorretor;
    private String[] columnNames = {"Título", "Status", "Nota", "Tentativas"};
    private DefaultTableModel dtm = new DefaultTableModel(columnNames, 0){
        // Deixa o table não-editável
        @Override
        public boolean isCellEditable(int row, int column){return false;}
        
        @Override
        public Class<?> getColumnClass(int column) {
            switch (column) {
                case 1: return ImageIcon.class;
                default: return String.class;
            }
        }
        
     };
    
    public PainelQuestoes(final PluginCorretor pluginCorretor) {
        this.pluginCorretor = pluginCorretor;
        iniciaTabela();
        initComponents();
        
        final TableCellRenderer tcrOs = jTable1.getTableHeader().getDefaultRenderer();
        jTable1.getTableHeader().setDefaultRenderer(new TableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, 
                   Object value, boolean isSelected, boolean hasFocus, 
                   int row, int column) {
                JLabel lbl = (JLabel) tcrOs.getTableCellRendererComponent(table, 
                      value, isSelected, hasFocus, row, column);
                
                lbl.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(new Color(128, 128, 128)),
                        BorderFactory.createEmptyBorder(1, 3, 1, 1)));
                lbl.setHorizontalAlignment(SwingConstants.LEFT);
                lbl.setForeground(Color.BLACK);
                lbl.setBackground(Color.WHITE);
                
                return lbl;
            }
        });
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(45);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(45);
        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    pluginCorretor.questaoSelecionada = row;
                    pluginCorretor.estado = 1;
                    pluginCorretor.atualizaPainel();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(dtm);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDoubleBuffered(true);
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Selecione um exercício:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void iniciaTabela() {
        for(PluginQuestao q : PluginCorretor.questoes){
            ImageIcon status = null;
            switch(q.getStatus()){
                case PluginQuestao.EM_ABERTO:
                    status = new ImageIcon(getClass().getResource("/org/univali/l2s/plugin/corretor/icones/flag_green.png"));
                    break;
                case PluginQuestao.PARCIAL:
                    status = new ImageIcon(getClass().getResource("/org/univali/l2s/plugin/corretor/icones/flag_yellow.png"));;
                    break;
                case PluginQuestao.FINALIZADO:
                    status = new ImageIcon(getClass().getResource("/org/univali/l2s/plugin/corretor/icones/flag_finish.png"));;
                    break;
            }
            Object[] colunas = new Object[4];
            colunas[0] = q.getQuestao().getTitulo();
            colunas[1] = status;
            colunas[2] = q.getMelhorNota();
            colunas[3] = q.getTentativas();
            dtm.addRow(colunas);
        }
    }
}
