/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.univali.l2s.plugin.corretor;

import br.univali.portugol.corretor.dinamico.model.Questao;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.transform.stream.StreamSource;

/**
 *
 * @author Andrei
 */
public class PluginSeletorQuestoes extends javax.swing.JFrame {
    
    private PainelCorretor painel;    
    private DefaultListModel model = new DefaultListModel();
    
    /**
     * Creates new form PluginSeletorQuestoes
     * @param painel
     */
    public PluginSeletorQuestoes(PainelCorretor painel) {
        
        
        initComponents();
        this.painel = painel;
        carregaQuestoes();
    }

    private PluginSeletorQuestoes() {
        initComponents();
        carregaQuestoes();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void carregaQuestoes(){
        String[] exercicios = new String[11];
        exercicios[0] = "exercicio14.pex";
        exercicios[1] = "exercicio18.pex";
        exercicios[2] = "exercicio27.pex";
        exercicios[3] = "exercicio29.pex";
        exercicios[4] = "exercicio30.pex";
        exercicios[5] = "exercicio34.pex";
        exercicios[6] = "exercicio40.pex";
        exercicios[7] = "exercicio45.pex";
        exercicios[8] = "exercicio47.pex";
        exercicios[9] = "exercicio57.pex";
        exercicios[10] = "exercicio60.pex";
        for (String e : exercicios) {
            model.addElement(e);
        }
      
    }
       
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {                
                new PluginSeletorQuestoes().setVisible(true);
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione uma Questão");

        jLabel1.setText("Selecione uma Questão:");

        jList1.setModel(model);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(evt.getClickCount()>1){    
            try {
                String str = (String) model.get(jList1.getSelectedIndex());
                File f = new File("C:/Users/Andrei/Dropbox/Projetos/Portugol/Projetos/Portugol-Studio-Recursos/exercicios/" + str);
                JAXBContext jc = JAXBContext.newInstance(Questao.class);
                Unmarshaller u = jc.createUnmarshaller();
                Questao questao = (Questao) u.unmarshal( new StreamSource(f) );
                this.painel.carregaQuestao(questao);
                this.dispose();
            } catch (JAXBException ex) {
                Logger.getLogger(PluginSeletorQuestoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
